use std::error::Error;

pub fn solve(input: &str) -> Result<String, Box<dyn Error>> {
	todo!("Part 1 solution not implemented")
}